"""Append Part C (continuous confidence) to confidence_analysis.ipynb."""
import json, pathlib

NB = pathlib.Path("notebooks/confidence_analysis.ipynb")
data = json.loads(NB.read_text(encoding="utf-8"))
cells = data["cells"]

def code_cell(source):
    return {"cell_type": "code", "execution_count": None,
            "metadata": {}, "outputs": [], "source": source}

def md_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

new_cells = []

# ── Part C header ─────────────────────────────────────────────────────────────
new_cells.append(md_cell(
    '---\n'
    '## Part C — Continuous Model Confidence\n'
    'For regression artifacts: does prediction magnitude |pred_return| correlate with quality?\n'
    '- **C1 (no data needed):** CV window IC vs decisiveness (mean |pred_return|).\n'
    '- **C2–C4 (requires DB):** inference on held-out data, magnitude threshold sweep, summary.\n'
))

# ── C1: CV Window IC vs Decisiveness ─────────────────────────────────────────
new_cells.append(md_cell(
    '### C1  CV Window: IC vs Decisiveness\n'
    '`mean_abs_pred` = mean of |predicted log return| across the window — a proxy for how strongly\n'
    'the model commits to a direction. Does higher commitment correlate with higher IC?\n'
))
new_cells.append(code_cell(
    'wdf_c_rows = []\n'
    'for stem, a in artifacts_cont.items():\n'
    '    for wi, m in enumerate(a[\'cv_metrics\']):\n'
    '        wdf_c_rows.append({\n'
    '            \'name\':          stem,\n'
    '            \'model\':         a[\'model_key\'],\n'
    '            \'window\':        wi,\n'
    '            \'ic\':            m.get(\'ic\', np.nan),\n'
    '            \'directional_accuracy\': m.get(\'directional_accuracy\', np.nan),\n'
    '            \'mean_abs_pred\': m.get(\'mean_abs_pred\', np.nan),\n'
    '        })\n'
    '\n'
    'wdf_c = pd.DataFrame(wdf_c_rows)\n'
    '\n'
    'if wdf_c.empty:\n'
    '    print("No continuous artifacts — Part C skipped.")\n'
    'else:\n'
    '    print(wdf_c.head())\n'
))
new_cells.append(code_cell(
    'if not wdf_c.empty:\n'
    '    models_c = wdf_c[\'name\'].unique()\n'
    '    ncols = min(3, len(models_c))\n'
    '    nrows = max(1, (len(models_c) + ncols - 1) // ncols)\n'
    '    fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 4 * nrows), squeeze=False)\n'
    '    palette = sns.color_palette(\'tab10\', len(models_c))\n'
    '\n'
    '    for ax, (name, color) in zip(axes.flat, zip(models_c, palette)):\n'
    '        sub = wdf_c[wdf_c[\'name\'] == name].dropna(subset=[\'mean_abs_pred\', \'ic\'])\n'
    '        if sub.empty:\n'
    '            ax.set_visible(False); continue\n'
    '        ax.scatter(sub[\'mean_abs_pred\'], sub[\'ic\'],\n'
    '                   color=color, alpha=0.75, s=60, edgecolors=\'white\', lw=0.5)\n'
    '        if len(sub) > 2:\n'
    '            m_, b_ = np.polyfit(sub[\'mean_abs_pred\'], sub[\'ic\'], 1)\n'
    '            x_ = np.linspace(sub[\'mean_abs_pred\'].min(), sub[\'mean_abs_pred\'].max(), 50)\n'
    '            ax.plot(x_, m_ * x_ + b_, color=\'black\', lw=1.2, ls=\'--\')\n'
    '            r, p = stats.pearsonr(sub[\'mean_abs_pred\'], sub[\'ic\'])\n'
    '            ax.set_title(f\'{name}\\nr={r:.2f}, p={p:.3f}\', fontsize=9)\n'
    '        else:\n'
    '            ax.set_title(name, fontsize=9)\n'
    '        ax.axhline(0, color=\'red\', lw=0.7, ls=\':\')\n'
    '        ax.set_xlabel(\'Decisiveness (mean |pred return|)\', fontsize=8)\n'
    '        ax.set_ylabel(\'IC (Spearman)\', fontsize=8)\n'
    '\n'
    '    for ax in axes.flat[len(models_c):]:\n'
    '        ax.set_visible(False)\n'
    '\n'
    '    plt.suptitle(\'Does higher prediction magnitude → better IC?\', fontsize=12, y=1.01)\n'
    '    plt.tight_layout(); plt.show()\n'
    '\n'
    '    # Correlation summary\n'
    '    corr_c_rows = []\n'
    '    for name, sub in wdf_c.groupby(\'name\'):\n'
    '        sub = sub.dropna(subset=[\'mean_abs_pred\', \'ic\'])\n'
    '        if len(sub) < 3: continue\n'
    '        r_ic,  p_ic  = stats.pearsonr(sub[\'mean_abs_pred\'], sub[\'ic\'])\n'
    '        r_da,  p_da  = stats.pearsonr(sub[\'mean_abs_pred\'], sub[\'directional_accuracy\'])\n'
    '        corr_c_rows.append({\n'
    '            \'artifact\': name,\n'
    '            \'model\': sub[\'model\'].iloc[0],\n'
    '            \'n_windows\': len(sub),\n'
    '            \'r(decisiveness, ic)\': f\'{r_ic:.3f} (p={p_ic:.3f})\',\n'
    '            \'r(decisiveness, dir_acc)\': f\'{r_da:.3f} (p={p_da:.3f})\',\n'
    '        })\n'
    '    if corr_c_rows:\n'
    '        display(pd.DataFrame(corr_c_rows).set_index(\'artifact\'))\n'
    '    else:\n'
    '        print("Not enough windows for correlation analysis.")\n'
))

# ── C2: Inference on held-out data (continuous) ───────────────────────────────
new_cells.append(md_cell(
    '---\n'
    '### C2  Inference on held-out data  (continuous)\n'
    'Loads each continuous final model and runs forward pass on dates after `train_end`.\n'
    'Returns `(date, ticker, actual_log_ret, pred_log_ret)`. No sigmoid — raw output is the predicted return.\n'
    '\n'
    '> **Requires SQLite DB access.**\n'
))
new_cells.append(code_cell(
    'def run_inference_continuous(artifact: dict, df_micro_raw, df_macro_raw) -> pd.DataFrame:\n'
    '    """Run continuous final model on dates after train_end.\n'
    '    Returns DataFrame with columns: date, ticker, actual, pred.\n'
    '    """\n'
    '    import torch\n'
    '\n'
    '    key       = artifact[\'model_key\']\n'
    '    horizon   = artifact[\'horizon\']\n'
    '    ft_type   = artifact[\'ft_type\']\n'
    '    train_end = pd.Timestamp(artifact[\'train_end\'])\n'
    '\n'
    '    df_macro_arg = df_macro_raw if ft_type == \'macro\' else None\n'
    '    # ml_ready returns y_discrete as 4th element; we need y_cont (5th)\n'
    '    df, X, y_disc, mask, y_cont = ml_ready(\n'
    '        horizon, df_micro_raw, df_macro=df_macro_arg, ft_type=ft_type\n'
    '    )\n'
    '\n'
    '    dates   = df.loc[mask, \'date\'].reset_index(drop=True)\n'
    '    tickers = df.loc[mask, \'ticker\'].reset_index(drop=True)\n'
    '    X = X.reset_index(drop=True)\n'
    '    y_cont = y_cont.reset_index(drop=True)\n'
    '\n'
    '    eval_mask = pd.to_datetime(dates) > train_end\n'
    '    if eval_mask.sum() == 0:\n'
    '        print(f\'  {key}: no held-out rows after {train_end.date()}\')\n'
    '        return pd.DataFrame()\n'
    '\n'
    '    if key in (\'xgb\',):\n'
    '        X_ev = X.loc[eval_mask]\n'
    '        preds = artifact[\'model\'].predict(X_ev)\n'
    '        return pd.DataFrame({\n'
    '            \'date\':   dates.loc[eval_mask].values,\n'
    '            \'ticker\': tickers.loc[eval_mask].values,\n'
    '            \'actual\': y_cont.loc[eval_mask].values,\n'
    '            \'pred\':   preds,\n'
    '        })\n'
    '\n'
    '    # --- neural (GRU, LSTM, CNN+GRU, CNN+LSTM) ---\n'
    '    from models.neural.lstm import add_cyclic_dow, build_sequences, SEQ_LEN\n'
    '    if \'dow\' in X.columns:\n'
    '        X = add_cyclic_dow(X.copy())\n'
    '\n'
    '    seqs, labs_disc, last_dates = build_sequences(X, y_disc, tickers, dates, SEQ_LEN)\n'
    '    # Rebuild labs using y_cont for the same sequence indices\n'
    '    _, labs_cont, _ = build_sequences(X, y_cont, tickers, dates, SEQ_LEN)\n'
    '\n'
    '    eval_date_set = set(dates.loc[eval_mask].values)\n'
    '    seq_mask = np.array([d in eval_date_set for d in last_dates])\n'
    '    seqs_ev  = seqs[seq_mask]\n'
    '    labs_ev  = labs_cont[seq_mask]\n'
    '    last_ev  = last_dates[seq_mask]\n'
    '\n'
    '    if len(seqs_ev) == 0:\n'
    '        print(f\'  {key}: no eval sequences\')\n'
    '        return pd.DataFrame()\n'
    '\n'
    '    sc = artifact[\'scaler\']\n'
    '    n, T, f = seqs_ev.shape\n'
    '    seqs_s = sc.transform(seqs_ev.reshape(-1, f)).reshape(n, T, f)\n'
    '\n'
    '    cfg = artifact[\'model_config\']\n'
    '    if \'num_filters\' in cfg:\n'
    '        from models.neural.cnn_rnn import StockCNNRNN\n'
    '        model = StockCNNRNN(**cfg)\n'
    '    else:\n'
    '        from models.neural.lstm import StockRNN\n'
    '        model = StockRNN(**cfg)\n'
    '    model.load_state_dict(artifact[\'model_state\'])\n'
    '    model.eval()\n'
    '\n'
    '    with torch.no_grad():\n'
    '        raw_out = model(torch.tensor(seqs_s, dtype=torch.float32))\n'
    '    # No sigmoid — raw output is predicted log return\n'
    '    preds = raw_out.numpy().flatten()\n'
    '\n'
    '    return pd.DataFrame({\n'
    '        \'date\':   last_ev,\n'
    '        \'actual\': labs_ev,\n'
    '        \'pred\':   preds,\n'
    '    })\n'
    '\n'
    '\n'
    '# --- collect ---\n'
    'if not artifacts_cont:\n'
    '    print("No continuous artifacts — skipping C2-C4.")\n'
    '    pred_data_cont = {}\n'
    'else:\n'
    '    from config import load_env\n'
    '    load_env()\n'
    '    # Reuse df_micro_raw / df_macro_raw if already loaded by Part B;\n'
    '    # otherwise load them here.\n'
    '    try:\n'
    '        df_micro_raw\n'
    '    except NameError:\n'
    '        df_micro_raw, df_macro_raw = _load_ohlcv()\n'
    '\n'
    '    pred_data_cont = {}\n'
    '    for name, a in artifacts_cont.items():\n'
    '        print(f\'Running continuous inference: {name} ...\')\n'
    '        df_pred = run_inference_continuous(a, df_micro_raw, df_macro_raw)\n'
    '        if len(df_pred) > 0:\n'
    '            pred_data_cont[name] = df_pred\n'
    '            print(f\'  -> {len(df_pred)} rows, \'\n'
    '                  f\'date range: {df_pred["date"].min()} -- {df_pred["date"].max()}\')\n'
    '\n'
    '    print(f\'\\nContinuous predictions collected for: {list(pred_data_cont.keys())}\')\n'
))

# ── C3: |pred_return| confidence filter sweep ────────────────────────────────
new_cells.append(md_cell(
    '### C3  |pred_return| as Confidence Filter\n'
    'Act only when |predicted return| ≥ δ. Sweep δ from 0 to the 90th percentile of |pred| in 20 steps.\n'
    'Shows coverage–directional_accuracy and coverage–IC curves.\n'
))
new_cells.append(code_cell(
    'from scipy.stats import spearmanr\n'
    '\n'
    'if not pred_data_cont:\n'
    '    print("No continuous prediction data.")\n'
    'else:\n'
    '    fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n'
    '\n'
    '    for name, df in pred_data_cont.items():\n'
    '        actuals  = df[\'actual\'].values\n'
    '        preds    = df[\'pred\'].values\n'
    '        abs_pred = np.abs(preds)\n'
    '\n'
    '        p90     = np.percentile(abs_pred, 90)\n'
    '        deltas  = np.linspace(0, p90, 20)\n'
    '        covs, dir_accs, ics = [], [], []\n'
    '\n'
    '        for delta in deltas:\n'
    '            keep = abs_pred >= delta\n'
    '            if keep.sum() < 10:\n'
    '                break\n'
    '            covs.append(keep.mean())\n'
    '            dir_accs.append(float(np.mean(np.sign(actuals[keep]) == np.sign(preds[keep]))))\n'
    '            ic_val, _ = spearmanr(actuals[keep], preds[keep])\n'
    '            ics.append(float(ic_val) if np.isfinite(ic_val) else 0.0)\n'
    '\n'
    '        axes[0].plot(covs, dir_accs, marker=\'o\', ms=4, lw=1.5, label=name)\n'
    '        axes[1].plot(covs, ics,      marker=\'o\', ms=4, lw=1.5, label=name)\n'
    '\n'
    '    axes[0].axhline(0.5, color=\'red\', ls=\'--\', lw=0.8, label=\'random\')\n'
    '    axes[0].set_title(\'Coverage–Directional Accuracy\', fontsize=11)\n'
    '    axes[0].set_xlabel(\'Coverage (fraction kept)\')\n'
    '    axes[0].set_ylabel(\'Directional accuracy\')\n'
    '    axes[0].xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1))\n'
    '    axes[0].legend(fontsize=8)\n'
    '\n'
    '    axes[1].axhline(0, color=\'red\', ls=\'--\', lw=0.8, label=\'IC=0\')\n'
    '    axes[1].set_title(\'Coverage–IC (Spearman)\', fontsize=11)\n'
    '    axes[1].set_xlabel(\'Coverage (fraction kept)\')\n'
    '    axes[1].set_ylabel(\'Spearman IC\')\n'
    '    axes[1].xaxis.set_major_formatter(mtick.PercentFormatter(xmax=1))\n'
    '    axes[1].legend(fontsize=8)\n'
    '\n'
    '    plt.suptitle(\'Does filtering on |pred_return| improve quality?\', fontsize=12, y=1.01)\n'
    '    plt.tight_layout(); plt.show()\n'
))

# ── C4: Summary metrics table ─────────────────────────────────────────────────
new_cells.append(md_cell('### C4  Summary — Continuous Inference Metrics'))
new_cells.append(code_cell(
    'from scipy.stats import spearmanr\n'
    'from sklearn.metrics import mean_absolute_error\n'
    '\n'
    'if not pred_data_cont:\n'
    '    print("No continuous prediction data.")\n'
    'else:\n'
    '    sum_rows_c = []\n'
    '    for name, df in pred_data_cont.items():\n'
    '        actuals = df[\'actual\'].values\n'
    '        preds   = df[\'pred\'].values\n'
    '        ic_val, _ = spearmanr(actuals, preds)\n'
    '        sum_rows_c.append({\n'
    '            \'artifact\':            name,\n'
    '            \'n_preds\':             len(df),\n'
    '            \'MAE\':                 f\'{mean_absolute_error(actuals, preds):.6f}\',\n'
    '            \'RMSE\':                f\'{np.sqrt(np.mean((actuals - preds)**2)):.6f}\',\n'
    '            \'IC (Spearman)\':       f\'{float(ic_val):.4f}\' if np.isfinite(ic_val) else \'nan\',\n'
    '            \'Directional Acc\':     f\'{np.mean(np.sign(actuals) == np.sign(preds)):.4f}\',\n'
    '        })\n'
    '\n'
    '    pd.DataFrame(sum_rows_c).set_index(\'artifact\').style \\\n'
    '        .set_caption(\'Continuous inference metrics on held-out data\') \\\n'
    '        .set_table_styles([{\'selector\': \'caption\',\n'
    '                            \'props\': \'font-size:13px; font-weight:bold;\'}])\n'
))

# ── Append all new cells ──────────────────────────────────────────────────────
cells.extend(new_cells)
data["cells"] = cells
NB.write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Appended {len(new_cells)} cells — confidence_analysis Part C done.")
